openapi: 3.0.0
info:
  title: API Documentation
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
tags:
  - name: Event
paths:
  /comedians:
    get:
      tags:
        - Comedian
      responses:
        200:
          description: All existing comedians
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ComedianResponse'
  /comedians/{comedianId}:
    get:
      tags:
        - Comedian
      parameters:
        - name: comedianId
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        201:
          description: Existing comedian
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ComedianResponse'
  /events:
    post:
      tags:
        - Event
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateEventRequest'
        required: true
      responses:
        201:
          description: New event created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventResponse'
    get:
      tags:
        - Event
      responses:
        200:
          description: All existing events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EventResponse'
  /events/{eventId}:
    get:
      tags:
        - Event
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        201:
          description: Existing event
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventResponse'
    put:
      tags:
        - Event
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateEventRequest'
        required: true
      responses:
        201:
          description: Event updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventResponse'
components:
  schemas:
    CreateEventRequest:
      title: CreateEventRequest
      required:
        - name
      type: object
      properties:
        name:
          type: string
        startDate:
          type: string
          format: date-time
        description:
          type: string
        poster:
          type: string
        price:
          type: number
        url:
          type: string
    UpdateEventRequest:
      title: UpdateEventRequest
      type: object
      properties:
        name:
          type: string
        startDate:
          type: string
          format: date-time
        description:
          type: string
        poster:
          type: string
        price:
          type: number
        url:
          type: string
    ContentResponse:
      title: ContentResponse
      required:
        - id
        - contentType
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        contentType:
          $ref: '#/components/schemas/ContentType'
        url:
          type: string
    ContentType:
      type: string
      enum:
        - SPOTIFY
        - PATREON
        - YOUTUBE
    EventResponse:
      title: EventResponse
      required:
        - id
        - name
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        date:
          type: string
          format: date-time
        description:
          type: string
        poster:
          type: string
        price:
          type: number
        url:
          type: string
        location:
          $ref: '#/components/schemas/Location'
        comedians:
          type: array
          items:
            $ref: '#/components/schemas/EventComedianResponse'
    ComedianEventResponse:
      title: ComedianEventResponse
      required:
        - id
        - name
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        date:
          type: string
          format: date-time
        description:
          type: string
        poster:
          type: string
        price:
          type: number
        url:
          type: string
        location:
          $ref: '#/components/schemas/Location'
    Location:
      title: Location
      required:
        - name
        - city
      properties:
        name:
          type: string
        city:
          type: string
        number:
          type: string
        street:
          type: string
    EventComedianResponse:
      title: EventComedianResponse
      required:
        - id
        - name
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        picture:
          type: string
    ComedianResponse:
      title: ComedianResponse
      required:
        - id
        - name
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        city:
          type: string
        picture:
          type: string
        instagram:
          type: string
        youtube:
          type: string
        tiktok:
          type: string
        twitter:
          type: string
        events:
          type: array
          items:
            $ref: '#/components/schemas/ComedianEventResponse'
        contents:
          type: array
          items:
            $ref: '#/components/schemas/ContentResponse'