openapi: 3.0.0
info:
  title: API Documentation
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
tags:
  - name: Event
paths:
  /comedians:
    get:
      tags:
        - Comedian
      parameters:
        - in: query
          name: pageable
          required: false
          schema:
            $ref: '#/components/schemas/Pageable'
        - in: query
          name: filters
          required: false
          allowReserved: true
          style: form
          explode: true
          schema:
            type: object
            properties:
              name:
                type: string
      responses:
        200:
          description: All existing comedians
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageComedianResponse'
    post:
      tags:
        - Comedian
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateComedianRequest'
        required: true
      responses:
        201:
          description: Comedian created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ComedianResponse'
  /comedians/{comedianId}:
    get:
      tags:
        - Comedian
      parameters:
        - name: comedianId
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        201:
          description: Existing comedian
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ComedianResponse'
    put:
      tags:
        - Comedian
      parameters:
        - name: comedianId
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateComedianRequest'
        required: true
      responses:
        201:
          description: Comedian updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ComedianResponse'
    delete:
      tags:
        - Comedian
      parameters:
        - name: comedianId
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        200:
          description: Comedian deleted
  /comedians/{comedianId}/events:
    get:
      tags:
        - Comedian
      parameters:
        - name: comedianId
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
        - in: query
          name: pageable
          required: false
          schema:
            $ref: '#/components/schemas/Pageable'
        - in: query
          name: filters
          required: false
          allowReserved: true
          style: form
          explode: true
          schema:
            type: object
            properties:
              dateFrom:
                type: string
                format: date-time
              dateTo:
                type: string
                format: date-time
      responses:
        200:
          description: All existing comedian events
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageComedianEventsResponse'
  /events:
    post:
      tags:
        - Event
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateEventRequest'
        required: true
      responses:
        201:
          description: New event created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventResponse'
    get:
      tags:
        - Event
      parameters:
        - in: query
          name: pageable
          required: false
          schema:
            $ref: '#/components/schemas/Pageable'
        - in: query
          name: filters
          required: false
          style: form
          explode: true
          schema:
            type: object
            properties:
              name:
                type: string
              city:
                type: string
              comedianId:
                type: integer
                format: int64
              dateFrom:
                type: string
                format: date-time
              dateTo:
                type: string
                format: date-time
              standupId:
                type: integer
                format: int64
      responses:
        200:
          description: All existing events
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageEventResponse'
  /events/{eventId}:
    get:
      tags:
        - Event
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        201:
          description: Existing event
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventResponse'
    put:
      tags:
        - Event
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateEventRequest'
        required: true
      responses:
        201:
          description: Event updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventResponse'
    delete:
      tags:
        - Event
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        200:
          description: Event deleted
  /locations:
    post:
      tags:
        - Location
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LocationInput'
        required: true
      responses:
        201:
          description: New location created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
    get:
      tags:
        - Location
      parameters:
        - in: query
          name: filters
          required: false
          schema:
            type: object
            properties:
              name:
                type: string
              city:
                type: string
      responses:
        200:
          description: All existing locations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Location'
  /locations/{locationId}:
    get:
      tags:
        - Location
      parameters:
        - name: locationId
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        201:
          description: Existing location
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
    put:
      tags:
        - Location
      parameters:
        - name: locationId
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LocationInput'
        required: true
      responses:
        201:
          description: Location updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
    delete:
      tags:
        - Location
      parameters:
        - name: locationId
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        200:
          description: Location deleted
  /standups:
    post:
      tags:
        - Standup
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StandupInput'
        required: true
      responses:
        201:
          description: New stand-up created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Standup'
    get:
      tags:
        - Standup
      responses:
        200:
          description: All existing stand-ups
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Standup'
  /standups/{standupId}:
    get:
      tags:
        - Standup
      parameters:
        - name: standupId
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        200:
          description: Existing stand-up
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Standup'
    put:
      tags:
        - Standup
      parameters:
        - name: standupId
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StandupInput'
        required: true
      responses:
        201:
          description: Stand-up updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Standup'
    delete:
      tags:
        - Standup
      parameters:
        - name: standupId
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        200:
          description: Stand-up deleted
  /login:
    post:
      tags:
        - Authentication
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        200:
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JwtToken'
components:
  schemas:
    CreateEventRequest:
      title: CreateEventRequest
      required:
        - name
      type: object
      properties:
        name:
          type: string
        date:
          type: string
          format: date-time
        description:
          type: string
        poster:
          type: string
        price:
          type: number
        url:
          type: string
        locationId:
          type: string
        standupId:
          type: string
        comedianIds:
          type: array
          items:
            type: string
    UpdateEventRequest:
      title: UpdateEventRequest
      type: object
      properties:
        name:
          type: string
        date:
          type: string
          format: date-time
        description:
          type: string
        poster:
          type: string
        price:
          type: number
        url:
          type: string
        locationId:
          type: string
        standupId:
          type: string
        comedianIds:
          type: array
          items:
            type: string
    ContentInput:
      title: ContentInput
      type: object
      properties:
        name:
          type: string
        contentType:
          $ref: '#/components/schemas/ContentType'
        url:
          type: string
    ContentResponse:
      title: ContentResponse
      required:
        - id
        - contentType
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        contentType:
          $ref: '#/components/schemas/ContentType'
        url:
          type: string
    ContentType:
      type: string
      enum:
        - SPOTIFY
        - PATREON
        - YOUTUBE
    PageEventResponse:
      title: PageEventResponse
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/EventResponse'
        totalElements:
          type: integer
        totalPages:
          type: integer
    PageComedianResponse:
      title: PageComedianResponse
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/ComedianResponse'
        totalElements:
          type: integer
        totalPages:
          type: integer
    EventResponse:
      title: EventResponse
      required:
        - id
        - name
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        date:
          type: string
          format: date-time
        description:
          type: string
        poster:
          type: string
        price:
          type: number
        url:
          type: string
        location:
          $ref: '#/components/schemas/Location'
        comedians:
          type: array
          items:
            $ref: '#/components/schemas/EventComedianResponse'
        standup:
          $ref: '#/components/schemas/Standup'
    ComedianEventResponse:
      title: ComedianEventResponse
      required:
        - id
        - name
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        date:
          type: string
          format: date-time
        description:
          type: string
        poster:
          type: string
        price:
          type: number
        url:
          type: string
        location:
          $ref: '#/components/schemas/Location'
        standup:
          $ref: '#/components/schemas/Standup'
    Location:
      title: Location
      required:
        - id
        - name
        - city
      properties:
        id:
          type: string
        name:
          type: string
        city:
          type: string
        number:
          type: string
        street:
          type: string
    LocationInput:
      title: Location
      required:
        - name
        - city
      properties:
        name:
          type: string
        city:
          type: string
        number:
          type: string
        street:
          type: string
    EventComedianResponse:
      title: EventComedianResponse
      required:
        - id
        - name
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        picture:
          type: string
    CreateComedianRequest:
      title: CreateComedianRequest
      required:
        - name
      type: object
      properties:
        name:
          type: string
        picture:
          type: string
        instagram:
          type: string
        youtube:
          type: string
        tiktok:
          type: string
        twitter:
          type: string
        contents:
          type: array
          items:
            $ref: '#/components/schemas/ContentInput'
    UpdateComedianRequest:
      title: UpdateComedianRequest
      type: object
      properties:
        name:
          type: string
        picture:
          type: string
        instagram:
          type: string
        youtube:
          type: string
        tiktok:
          type: string
        twitter:
          type: string
        contents:
          type: array
          items:
            $ref: '#/components/schemas/ContentInput'
    ComedianResponse:
      title: ComedianResponse
      required:
        - id
        - name
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        city:
          type: string
        picture:
          type: string
        instagram:
          type: string
        youtube:
          type: string
        tiktok:
          type: string
        twitter:
          type: string
        contents:
          type: array
          items:
            $ref: '#/components/schemas/ContentResponse'
    Standup:
      title: Standup
      required:
        - id
        - name
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        poster:
          type: string
    StandupInput:
      title: StandupInput
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        poster:
          type: string
    PageComedianEventsResponse:
      title: PageComedianEventsResponse
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/ComedianEventResponse'
        totalElements:
          type: integer
        totalPages:
          type: integer
    Pageable:
      description: Pageable query parameters
      type: object
      properties:
        page:
          type: integer
          default: 0
        size:
          type: integer
          default: 10
    Page:
      description: Pageable query parameters
      type: object
      properties:
        total:
          type: integer
          default: 0
        content:
          type: object
    LoginRequest:
      title: LoginRequest
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string
    JwtToken:
      title: JwtToken
      type: object
      required:
        - accessToken
      properties:
        accessToken:
          type: string