openapi: 3.0.0
info:
  title: API Documentation
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
tags:
  - name: Event
paths:
  /comedians:
    get:
      tags:
        - Comedian
      responses:
        200:
          description: All existing comedians
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ComedianResponse'
  /comedians/{comedianId}:
    get:
      tags:
        - Comedian
      parameters:
        - name: comedianId
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        201:
          description: Existing comedian
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ComedianResponse'
  /events:
    post:
      tags:
        - Event
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateEventRequest'
        required: true
      responses:
        201:
          description: New event created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventResponse'
    get:
      tags:
        - Event
      responses:
        200:
          description: All existing events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EventResponse'
  /events/{eventId}:
    get:
      tags:
        - Event
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        201:
          description: Existing event
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventResponse'
    put:
      tags:
        - Event
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateEventRequest'
        required: true
      responses:
        201:
          description: Event updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventResponse'
components:
  schemas:
    CreateEventRequest:
      title: CreateEventRequest
      required:
        - name
      type: object
      properties:
        name:
          type: string
        startDate:
          type: string
          format: date-time
        description:
          type: string
        poster:
          type: string
        price:
          type: number
        url:
          type: string
    UpdateEventRequest:
      title: UpdateEventRequest
      type: object
      properties:
        name:
          type: string
        startDate:
          type: string
          format: date-time
        description:
          type: string
        poster:
          type: string
        price:
          type: number
        url:
          type: string
    EventResponse:
      title: EventResponse
      required:
        - id
        - name
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        startDate:
          type: string
          format: date-time
        description:
          type: string
        poster:
          type: string
        price:
          type: number
        url:
          type: string
    ComedianResponse:
      title: ComedianResponse
      required:
        - id
        - name
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        city:
          type: string
        picture:
          type: string
        instagram:
          type: string
        youtube:
          type: string
        tiktok:
          type: string