server:
  servlet:
    context-path: /api
spring:
  datasource:
    url: ${GIGGZ_DATABASE_URL}
    #LOCAL CONFIG. get these values from vault or somewhere in the prod config
    password: ${GIGGZ_DATABASE_PASSWORD}
    username: ${GIGGZ_DATABASE_USERNAME}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    #possibly to remove in the future
#    generate-ddl: true
    show-sql: true
    #to remove in the future
#    hibernate:
#      ddl-auto: none
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            clientId: ENC(L4LsD/n9utILxUCzQ9nmUiG7O9WFLUpDUrpovKm12vk0aawX6P0K0kqTMhhwh0LsfJJdLU/L92H9pCn+sSeGLs3D0lUiZz9qeFdu1S6XyhnCnsF8tti6xw==)
#            clientSecret: ENC(jLBFCSLAujDKxkFc3fvgGwK/pEgJP5QPc1nD37L1cU6lDm7m1x/9a9Tl3vrwAHYQ)