server:
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:postgresql://${GIGGZ_DATABASE_URL}
    password: ${GIGGZ_DATABASE_PASSWORD}
    username: ${GIGGZ_DATABASE_USERNAME}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        #possibly to remove in the future
        show-sql: false
    #to remove in the future
    hibernate:
     ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GIGGZ_GOOGLE_CLIENT_ID}
            clientSecret: ${GIGGZ_GOOGLE_CLIENT_SECRET}
logging:
  level:
    org.springframework.security: DEBUG

youtube:
  api:
    key: ${YOUTUBE_API_KEY}
